### ISSUE TITLE
Classification must be performed in tandem with motor-moving

### ISSUE THREAD

**Issue by reubendocea** [poganyg/Glassify#6]
The motor must react to the changing of state from the classification from rest to the presence of a bottle.

**Comment by Docea** [comment]
This has been achieved by passing pointers to a 'state' class to both the classification object and the motor thread object and monitoring this state through a 'mutex' variable

**Comment by reubendocea** [comment]
This has been achieved by passing pointers to a 'state' class to both the classification object and the motor thread object and monitoring this state through a 'mutex' variable
