### ISSUE TITLE
Classifier object and Motor object read&write to same pointer

### ISSUE THREAD

**Issue by reubendocea** [poganyg/Glassify#7]
Classifier object and Motor object read&write to same pointer causing segmentation fault.

This may be solved by creating a second pointer variable which indicates to either thread that it is ok to access the variable

**Comment by Docea** [comment]
Solved -- threads access same memory via class-based pointer and 'mutex'

**Comment by reubendocea** [comment]
Solved -- threads access same memory via class-based pointer and 'mutex'
